### ISSUE TITLE
对您的这个项目很看好，试用了下，发现刷新时页面特别慢，大概需要5秒左右。

### ISSUE THREAD

**Issue by jiangnan2018** [SmallRuralDog/amis-admin#5]
![image](https://user-images.githubusercontent.com/16172085/200988212-75c39a58-dbae-4b72-8e14-643d6f3e1c7a.png)

也么看到，public下文件重新编译！
这是为何呢，能用于生产环境不？

**Comment by SmallRuralDog** [comment]
环境发一下
