### ISSUE TITLE
src/Components/ModelBase 引用文件问题

### ISSUE THREAD

**Issue by oscar-mx** [SmallRuralDog/amis-admin#7]
大佬, 项目很不错 , 但是本地安装后,跑起来, 发现表单删除报错

看了源码 发现 src/Components/ModelBase.php  里目前引用的**Illuminate\Contracts\Database\Query\Builder**  手动更换成**Illuminate\Database\Eloquent\Builder** 后更新正常

这里是不是有点小问题哈?
![image](https://user-images.githubusercontent.com/53085808/215994026-76c38830-c58f-41b4-b55b-09d96365afb4.png)

![image](https://user-images.githubusercontent.com/53085808/215993942-62d23475-c46f-4bc5-99bf-cc55b4361454.png)
![image](https://user-images.githubusercontent.com/53085808/215994316-62de6da0-b7f5-49f9-9fa2-0f771393d9ab.png)

**Comment by SmallRuralDog** [comment]
感谢！！
