### ISSUE TITLE
Method Illuminate\Support\Stringable::toString does not exist. 使用laravel8.x 安装后出现此问题

### ISSUE THREAD

**Issue by cmxStarCoding** [SmallRuralDog/amis-admin#8]
![问题1](https://user-images.githubusercontent.com/92977410/221412582-2aa08ab1-3e0d-46f9-94b6-920c335506df.png)

使用laravel8.x 安装后出现此问题，在对应类vendor/laravel/framework/src/Illuminate/Support/Stringable.php添加
![image](https://user-images.githubusercontent.com/92977410/221412492-84672bca-c222-4565-ab81-b69aeb04e67f.png)
问题消失，是否存在版本兼容问题

**Comment by SmallRuralDog** [comment]
使用的具体版本号是多少

**Comment by cmxStarCoding** [comment]
> 使用的具体版本号是多少

![image](https://user-images.githubusercontent.com/92977410/225497198-3327e519-f13b-4a52-ae0d-f9d3dceea53b.png)

**Comment by SnoW-Wei** [comment]
我也遇到这个问题

**Comment by SmallRuralDog** [comment]
已修复
